version: '3.8'
services:
  app:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app:delegated
    working_dir: /app
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
    restart: unless-stopped

